listen_addr: "127.0.0.1:3000"
# TLS configuration - uncomment to enable TLS
tls:
  cert_path: "./certs/cert.pem"
  key_path: "./certs/key.pem"

# Health check configuration
health_check:
  enabled: true
  interval_secs: 10
  timeout_secs: 5
  path: "/health"      # Default path to check
  unhealthy_threshold: 3
  healthy_threshold: 2

# Backend-specific health check paths
backend_health_paths:
  "https://httpbin.org": "/get"
  "https://postman-echo.com": "/get"
  "https://jsonplaceholder.typicode.com": "/todos/1"

routes:
  "/":  # Add root route that redirects to /static
    type: "redirect"
    target: "/static"
    status_code: 302
  "/static":
    type: "static"
    root: "./static"
  "/redirect":
    type: "redirect"
    target: "https://www.example.com"
    status_code: 302
  "/proxy":
    type: "proxy"
    target: "https://httpbin.org"
    path_rewrite: "/anything" # Example: rewrite /proxy/foo to /anything/foo
    rate_limit: # Example: Limit by IP, 10 requests per minute
      by: "ip"
      requests: 10
      period: "1m"
      # status_code: 429 # Optional: defaults to 429
      # message: "Too many requests from your IP. Please try again later." # Optional: defaults to "Too Many Requests"
      # algorithm: "token_bucket" # Optional: defaults to token_bucket
  "/api/v1":
    type: "proxy"
    target: "https://jsonplaceholder.typicode.com" # Assuming this is a placeholder for a real internal service
    path_rewrite: "/" # Example: rewrite /api/v1/users to /users on the backend
    rate_limit: # Example: Limit by a specific header X-API-Key, 5 requests per 30 seconds
      by: "header"
      header_name: "X-API-Key"
      requests: 5
      period: "30s"
      status_code: 403
      message: "Rate limit exceeded for your API key."
  "/balance":
    type: "load_balance"
    targets:
      - "https://httpbin.org"
      - "https://postman-echo.com"
    strategy: "round_robin"
    path_rewrite: "/anything" # Changed from /newpath to /anything to use a common echo endpoint
    rate_limit: # Example: Route-wide limit, 100 requests per hour
      by: "route"
      requests: 100
      period: "1h"