listen_addr: "127.0.0.1:3000"
# TLS configuration - uncomment to enable TLS
tls:
  cert_path: "./certs/cert.pem"
  key_path: "./certs/key.pem"

# Health check configuration
health_check:
  enabled: true
  interval_secs: 10
  timeout_secs: 5
  path: "/health"      # Default path to check
  unhealthy_threshold: 3
  healthy_threshold: 2

# Backend-specific health check paths
backend_health_paths:
  "https://httpbin.org": "/get"
  "https://postman-echo.com": "/get"
  "https://jsonplaceholder.typicode.com": "/todos/1"

routes:
  "/":  # Add root route that redirects to /static
    type: "redirect"
    target: "/static"
    status_code: 302
  "/static":
    type: "static"
    root: "./static"
  "/redirect":
    type: "redirect"
    target: "https://www.example.com"
    status_code: 302
  "/proxy":
    type: "proxy"
    target: "https://httpbin.org"
    path_rewrite: "/anything" # Example: rewrite /proxy/foo to /anything/foo
  "/api/v1":
    type: "proxy"
    target: "https://jsonplaceholder.typicode.com" # Assuming this is a placeholder for a real internal service
    path_rewrite: "/" # Example: rewrite /api/v1/users to /users on the backend
  "/balance":
    type: "load_balance"
    targets:
      - "https://httpbin.org"
      - "https://postman-echo.com"
    strategy: "round_robin"
    path_rewrite: "/anything" # Changed from /newpath to /anything to use a common echo endpoint