listen_addr: "127.0.0.1:3000"
# TLS configuration
tls:
  cert_path: "./certs/cert.pem"
  key_path: "./certs/key.pem"

# Health check configuration
health_check:
  enabled: true
  interval_secs: 10
  timeout_secs: 5
  path: "/health"      # Default path to check
  unhealthy_threshold: 3
  healthy_threshold: 2

# Backend-specific health check paths
backend_health_paths:
  "https://jsonplaceholder.typicode.com": "/posts/1"
  "https://httpbin.org": "/get"

routes:
  "/static":
    type: "static"
    root: "./static"
  "/redirect":
    type: "redirect"
    target: "https://www.example.com"
    status_code: 302
  "/proxy":
    type: "proxy"
    target: "https://jsonplaceholder.typicode.com"
  "/balance":
    type: "load_balance"
    targets:
      - "https://jsonplaceholder.typicode.com"
      - "https://httpbin.org"
    strategy: "round_robin"