# See https://embarkstudios.github.io/cargo-deny/ for comprehensive configuration options

# Deny all advisories by default.
# You can specify `severity-threshold` or `ignore` specific advisories if needed.
[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn" # Or "deny" if you want to be stricter
notice = "warn"
ignore = [
    # "RUSTSEC-XXXX-XXXX", # Example: Ignore a specific advisory
]
# severity-threshold = "medium" # Example: Only deny advisories with medium severity or higher

# Configure license checks.
[licenses]
unlicensed = "deny" # Deny crates that don't have a license specified
allow = [ # List of allowed licenses
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "Unlicense", # If you accept this
]
# deny = [] # List of explicitly denied licenses
# You can also specify `default = "warn"` or `default = "allow"`
# and then use `allow`/`deny` for exceptions.
# For private projects, you might not need to be as strict.
# For open source, it's good practice to define allowed licenses.
copyleft = "warn" # Warn on copyleft licenses like GPL, AGPL, LGPL
# allow-osi-fsf-free = "neither" # How to handle OSI/FSF approved licenses
# private = { ignore = true } # Ignore private workspace crates

# Check for banned crates or versions.
[bans]
multiple-versions = "warn" # Warn if multiple versions of the same crate are found
# skip = [] # List of crates to skip for multiple-versions check
# skip-tree = [] # List of crates and their entire dependency trees to skip
# deny = [ # List of crates to deny
    # { name = "openssl", version = "<0.10.30" }, # Example: Deny old versions of openssl
    # { name = "some-problematic-crate" },
# ]
# allow = [] # List of crates to explicitly allow, even if they match a deny rule

# Configure how sources are handled (e.g., crates.io, git repositories).
[sources]
unknown-registry = "warn" # Warn if a crate comes from an unknown registry
unknown-git = "warn"    # Warn if a crate comes from an unknown git repository
allow-git = [           # List of allowed git repositories
    # "https://github.com/your-org/your-private-crate",
]
# allow-registry = ["https://my-internal-registry.com"] # List of allowed registries
# required-git-spec = "branch" # e.g. "tag", "rev", "branch", "any"
