apiVersion: v1
kind: ConfigMap
metadata:
  name: prox-config
  namespace: default
data:
  config.yaml: |
    listen_addr: "0.0.0.0:8080"
    
    # Manual TLS configuration (self-signed certs in container)
    tls:
      cert_path: "./certs/cert.pem"
      key_path: "./certs/key.pem"
    
    # Health check configuration
    health_check:
      enabled: true
      interval_secs: 10
      timeout_secs: 5
      path: "/health"
      unhealthy_threshold: 3
      healthy_threshold: 2
    
    routes:
      "/":  # Root route that redirects to /static
        type: "redirect"
        target: "/static"
        status_code: 302
      "/static":
        type: "static"
        root: "./static"
      "/health":
        type: "static"
        root: "./static"
      "/proxy":
        type: "proxy"
        target: "https://httpbin.org"
        path_rewrite: "/anything"
        request_headers:
          add:
            "X-Forwarded-By": "Prox-K8s"
            "X-Real-IP": "{client_ip}"
      "/balance":
        type: "load_balance"
        targets:
          - "https://httpbin.org"
          - "https://postman-echo.com" 
        strategy: "round_robin"
        path_rewrite: "/anything"
